import { getDb } from "../api/queries/connection";
import {
  categories,
  products,
  settings,
  deliveryCompanies,
} from "./schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // Seed delivery companies
  await db.insert(deliveryCompanies).values([
    { name: "Yalidine", phone: "023 23 23 23", isActive: true },
    { name: "Ecotrans", phone: "024 24 24 24", isActive: true },
    { name: "Commodore", phone: "025 25 25 25", isActive: true },
  ]);
  console.log("Delivery companies seeded");

  // Seed categories
  await db.insert(categories).values([
    {
      nameEn: "Baby Boys",
      nameFr: "Garçon",
      nameAr: "أولاد",
      slug: "baby-boys",
      descriptionEn: "Premium clothing for baby boys",
      descriptionFr: "Vêtements premium pour bébés garçons",
      descriptionAr: "ملابس ممتازة للأولاد",
      image: "/images/cat-baby-boys.jpg",
      sortOrder: 1,
    },
    {
      nameEn: "Baby Girls",
      nameFr: "Fille",
      nameAr: "بنات",
      slug: "baby-girls",
      descriptionEn: "Premium clothing for baby girls",
      descriptionFr: "Vêtements premium pour bébés filles",
      descriptionAr: "ملابس ممتازة للبنات",
      image: "/images/cat-baby-girls.jpg",
      sortOrder: 2,
    },
    {
      nameEn: "Newborn",
      nameFr: "Nouveau-né",
      nameAr: "حديثي الولادة",
      slug: "newborn",
      descriptionEn: "Soft essentials for newborns",
      descriptionFr: "Essentiels doux pour les nouveau-nés",
      descriptionAr: "مستلزمات ناعمة لحديثي الولادة",
      image: "/images/cat-newborn.jpg",
      sortOrder: 3,
    },
    {
      nameEn: "Accessories",
      nameFr: "Accessoires",
      nameAr: "إكسسوارات",
      slug: "accessories",
      descriptionEn: "Baby accessories and more",
      descriptionFr: "Accessoires pour bébé",
      descriptionAr: "إكسسوارات الأطفال",
      image: "/images/cat-accessories.jpg",
      sortOrder: 4,
    },
  ]);
  console.log("Categories seeded");

  // Get category IDs
  const allCats = await db.select().from(categories);
  const getCatId = (slug: string) => allCats.find(c => c.slug === slug)?.id;

  // Seed products
  await db.insert(products).values([
    {
      nameEn: "Bear Pajama Set",
      nameFr: "Pyjama Ours",
      nameAr: "طقم بيجاما دب",
      slug: "bear-pajama-set",
      descriptionEn: "Soft cotton pajama set with cute bear embroidery. Perfect for comfortable sleep.",
      descriptionFr: "Pyjama en coton doux avec broderie ours mignon. Parfait pour dormir confortablement.",
      descriptionAr: "طقم بيجاما قطني ناعم بتطريز دب لطيف. مثالي للنوم المريح.",
      price: "1950.00",
      oldPrice: "2400.00",
      sku: "ABI-001",
      stockQuantity: 25,
      stockLocation: "Algiers Warehouse",
      warehouseWilaya: "Algiers",
      categoryId: getCatId("baby-boys"),
      images: JSON.stringify(["/images/prod-boys-pajama.jpg"]),
      colors: JSON.stringify(["Mint", "Blue"]),
      sizes: JSON.stringify(["NN", "1A", "2A", "12m", "18m", "24m"]),
      isActive: true,
      isFeatured: true,
      isNewArrival: true,
    },
    {
      nameEn: "Floral Dress",
      nameFr: "Robe Florale",
      nameAr: "فستان زهور",
      slug: "floral-dress",
      descriptionEn: "Beautiful floral embroidered dress with matching bloomers. Made with premium cotton.",
      descriptionFr: "Belle robe à broderie florale avec bloomer assorti. Fait en coton premium.",
      descriptionAr: "فستان جميل بتطريز زهري مع سروال مطابق. مصنوع من قطن ممتاز.",
      price: "2200.00",
      oldPrice: "2800.00",
      sku: "ABI-002",
      stockQuantity: 18,
      stockLocation: "Algiers Warehouse",
      warehouseWilaya: "Algiers",
      categoryId: getCatId("baby-girls"),
      images: JSON.stringify(["/images/prod-girls-dress.jpg"]),
      colors: JSON.stringify(["Pink", "White"]),
      sizes: JSON.stringify(["1A", "2A", "3A", "12m", "18m", "24m"]),
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      nameEn: "Organic Onesie",
      nameFr: "Body Bio",
      nameAr: "بودي قطني عضوي",
      slug: "organic-onesie",
      descriptionEn: "Pure organic cotton onesie with natural wooden buttons. Gentle on newborn skin.",
      descriptionFr: "Body en coton bio pur avec boutons en bois naturel. Doux pour la peau des nouveau-nés.",
      descriptionAr: "بودي قطن عضوي نقي بأزرار خشبية طبيعية. ناعم على بشرة حديثي الولادة.",
      price: "1200.00",
      sku: "ABI-003",
      stockQuantity: 40,
      stockLocation: "Oran Warehouse",
      warehouseWilaya: "Oran",
      categoryId: getCatId("newborn"),
      images: JSON.stringify(["/images/prod-newborn-onesie.jpg"]),
      colors: JSON.stringify(["White", "Cream", "Mint"]),
      sizes: JSON.stringify(["NN", "1A", "2A", "3A"]),
      isActive: true,
      isFeatured: true,
      isNewArrival: true,
    },
    {
      nameEn: "Cotton Blanket",
      nameFr: "Couverture Coton",
      nameAr: "بطانية قطنية",
      slug: "cotton-blanket",
      descriptionEn: "Luxuriously soft woven cotton blanket. Perfect for swaddling and comfort.",
      descriptionFr: "Couverture en coton tissé luxueusement douce. Parfaite pour l'emmaillotage.",
      descriptionAr: "بطانية قطنية محبوكة فاخرة وناعمة. مثالية للتقميط والراحة.",
      price: "1850.00",
      oldPrice: "2200.00",
      sku: "ABI-004",
      stockQuantity: 15,
      stockLocation: "Algiers Warehouse",
      warehouseWilaya: "Algiers",
      categoryId: getCatId("accessories"),
      images: JSON.stringify(["/images/prod-blanket.jpg"]),
      colors: JSON.stringify(["Mint", "Pink", "Beige"]),
      sizes: JSON.stringify(["One Size"]),
      isActive: true,
      isFeatured: false,
      isBestseller: true,
    },
    {
      nameEn: "Cloud Romper",
      nameFr: "Barboteuse Nuage",
      nameAr: "رومبر سحابة",
      slug: "cloud-romper",
      descriptionEn: "Adorable romper with cloud appliqué. Short sleeves for summer comfort.",
      descriptionFr: "Barboteuse adorable avec appliqué nuage. Manches courtes pour le confort estival.",
      descriptionAr: "رومبر رائع بتصميم سحابة. أكمام قصيرة لراحة الصيف.",
      price: "1450.00",
      sku: "ABI-005",
      stockQuantity: 30,
      stockLocation: "Algiers Warehouse",
      warehouseWilaya: "Algiers",
      categoryId: getCatId("baby-boys"),
      images: JSON.stringify(["/images/prod-romper-yellow.jpg"]),
      colors: JSON.stringify(["Yellow", "Mint", "White"]),
      sizes: JSON.stringify(["NN", "1A", "2A", "12m", "18m"]),
      isActive: true,
      isFeatured: false,
      isNewArrival: true,
    },
    {
      nameEn: "Bunny Bodysuit",
      nameFr: "Body Lapin",
      nameAr: "بودي أرنب",
      slug: "bunny-bodysuit",
      descriptionEn: "Soft pink bodysuit with fluffy bunny applique. Long sleeves for warmth.",
      descriptionFr: "Body rose doux avec appliqué lapin moelleux. Manches longues pour la chaleur.",
      descriptionAr: "بودي وردي ناعم بتصميم أرنب ناعم. أكمام طويلة للدفء.",
      price: "1550.00",
      oldPrice: "1900.00",
      sku: "ABI-006",
      stockQuantity: 22,
      stockLocation: "Oran Warehouse",
      warehouseWilaya: "Oran",
      categoryId: getCatId("baby-girls"),
      images: JSON.stringify(["/images/prod-bunny-bodysuit.jpg"]),
      colors: JSON.stringify(["Pink", "White"]),
      sizes: JSON.stringify(["NN", "1A", "2A", "3A", "12m"]),
      isActive: true,
      isFeatured: true,
      isBestseller: false,
    },
    {
      nameEn: "Star T-Shirt Set",
      nameFr: "Ensemble T-Shirt Étoile",
      nameAr: "طقم تيشيرت نجوم",
      slug: "star-tshirt-set",
      descriptionEn: "Comfortable t-shirt and shorts set with star pattern. Perfect for everyday wear.",
      descriptionFr: "Ensemble t-shirt et short confortable avec motif étoile. Parfait pour le quotidien.",
      descriptionAr: "طقم تيشيرت وشورت مريح بنمط نجوم. مثالي للاستخدام اليومي.",
      price: "1650.00",
      sku: "ABI-007",
      stockQuantity: 20,
      stockLocation: "Constantine Warehouse",
      warehouseWilaya: "Constantine",
      categoryId: getCatId("baby-boys"),
      images: JSON.stringify(["/images/prod-boys-set.jpg"]),
      colors: JSON.stringify(["Grey", "Mint"]),
      sizes: JSON.stringify(["1A", "2A", "3A", "12m", "18m", "24m"]),
      isActive: true,
      isFeatured: false,
      isNewArrival: true,
    },
    {
      nameEn: "Sleeping Bag",
      nameFr: "Gigoteuse",
      nameAr: "كيس نوم",
      slug: "sleeping-bag",
      descriptionEn: "Quilted sleeping bag with moon and star embroidery. Keeps baby warm and safe.",
      descriptionFr: "Gigoteuse matelassée avec broderie lune et étoile. Garde bébé au chaud et en sécurité.",
      descriptionAr: "كيس نوم مبطن بتطريز القمر والنجوم. يبقي الطفل دافئاً وآمناً.",
      price: "2450.00",
      oldPrice: "2900.00",
      sku: "ABI-008",
      stockQuantity: 12,
      stockLocation: "Algiers Warehouse",
      warehouseWilaya: "Algiers",
      categoryId: getCatId("newborn"),
      images: JSON.stringify(["/images/prod-sleeping-bag.jpg"]),
      colors: JSON.stringify(["Mint", "Blue"]),
      sizes: JSON.stringify(["NN", "1A", "2A"]),
      isActive: true,
      isFeatured: true,
      isBestseller: true,
    },
    {
      nameEn: "Bib Set (2 pcs)",
      nameFr: "Lot de Bavoirs (2 pcs)",
      nameAr: "طقم مرايل (2 قطع)",
      slug: "bib-set",
      descriptionEn: "Set of 2 soft cotton bibs with snap closure. One mint and one pink.",
      descriptionFr: "Lot de 2 bavoirs en coton doux avec fermeture à pression. Un menthe et un rose.",
      descriptionAr: "طقم مريلين قطنيين ناعمين بإغلاق سناً. واحد نعناعي وواحد وردي.",
      price: "850.00",
      sku: "ABI-009",
      stockQuantity: 35,
      stockLocation: "Oran Warehouse",
      warehouseWilaya: "Oran",
      categoryId: getCatId("accessories"),
      images: JSON.stringify(["/images/prod-bib-set.jpg"]),
      colors: JSON.stringify(["Mint", "Pink"]),
      sizes: JSON.stringify(["One Size"]),
      isActive: true,
      isFeatured: false,
      isNewArrival: false,
    },
    {
      nameEn: "Knitted Hat & Booties",
      nameFr: "Bonnet & Chaussons Tricot",
      nameAr: "قبعة وشرابات محبوكة",
      slug: "knitted-hat-booties",
      descriptionEn: "Hand-knitted hat with pom pom and matching booties. Warm and adorable.",
      descriptionFr: "Bonnet tricoté à la main avec pompon et chaussons assortis. Chaud et adorable.",
      descriptionAr: "قبعة محبوكة يدوياً بكرة بوم بوم وشرابات مطابقة. دافئة ورائعة.",
      price: "950.00",
      oldPrice: "1200.00",
      sku: "ABI-010",
      stockQuantity: 18,
      stockLocation: "Constantine Warehouse",
      warehouseWilaya: "Constantine",
      categoryId: getCatId("accessories"),
      images: JSON.stringify(["/images/prod-hat-booties.jpg"]),
      colors: JSON.stringify(["Beige", "White", "Pink"]),
      sizes: JSON.stringify(["NN", "1A", "2A"]),
      isActive: true,
      isFeatured: false,
      isBestseller: false,
    },
  ]);
  console.log("Products seeded");

  // Seed settings
  await db.insert(settings).values([
    { key: "storeName", value: "ABI MOD" },
    { key: "storeEmail", value: "abi-mod@outlook.com" },
    { key: "storePhone", value: "0798 43 65 28" },
    { key: "whatsappNumber", value: "213798436528" },
    { key: "whatsappMessage", value: "Hello ABI MOD! I have a question about your products." },
    { key: "facebookUrl", value: "https://facebook.com/abimod" },
    { key: "instagramUrl", value: "https://instagram.com/abimod" },
    { key: "currency", value: "DZD" },
  ]);
  console.log("Settings seeded");

  console.log("Seed complete!");
}

seed().catch(console.error);
